Feat: ssr refactor (#232)
Co-authored-by: antondlr <anton@delaruelle.net>
Co-authored-by: Jimmy Chen <jchen.tc@gmail.com>
Co-authored-by: Age Manning <Age@AgeManning.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,21 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npx lint-staged && npx tsc --project tsconfig.json && yarn test
+export PATH="/Users/rickimoore/lighthouse-ui:$PATH"
+
+# Run the Next.js linter with auto-fixing
+npx next lint --fix
+
+# Run Jest tests using yarn
+yarn test
+
+# Navigate to the backend directory
+cd backend
+
+yarn test
+
+# Check if the Jest tests passed
+if [ $? -ne 0 ]; then
+  echo "Jest tests failed. Aborting commit."
+  exit 1
+fi
